#!/bin/sh

modules=$(find /lib/modules/"$(uname -r)" -type f -name '*.ko')

worker() {
    for module in $modules; do
        $1 "$module"
    done
}

case "$1" in
    start)
        worker insmod;;
    stop)
        worker rmmod;;
    *)
        echo "Usage: $0 <start|stop>"
        exit 1
esac
